# Generated by Django 5.1 on 2024-08-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lp', '0003_getquoteassuarance_remove_getquote_assuarance'),
    ]

    operations = [
        migrations.AddField(
            model_name='getquote',
            name='desired_date_of_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='getquote',
            name='method_of_appointment',
            field=models.CharField(blank=True, choices=[('In-person', 'In-person'), ('Video-call', 'Video-call'), ('Phonecall', 'Phonecall')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='getquote',
            name='service_of_inquiry',
            field=models.CharField(choices=[('Digital/IT Strategy Development', 'Digital/IT Strategy Development'), ('Digital Transformation Advisory', 'Digital Transformation Advisory'), ('Crisis Management Consultancy', 'Crisis Management Consultancy'), ('IT Service Delivery and Management (ITSM)', 'IT Service Delivery and Management (ITSM)'), ('Project Management', 'Project Management'), ('Digital Branding and Marketing', 'Digital Branding and Marketing'), ('Start-up Digital Consulting', 'Start-up Digital Consulting')], max_length=150),
        ),
    ]
